import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";

const MAX_BYTES = 5 * 1024 * 1024;
const MAX_LEAVES = 100_000;
const dangerousKeys = new Set(["__proto__", "prototype", "constructor"]);
const packDirectory = new URL("../v1/whitebox/", import.meta.url);

function stringLeaves(value, path) {
  if (typeof value === "string") return 1;
  assert(value && typeof value === "object" && !Array.isArray(value), `${path} must be an object`);
  let count = 0;
  for (const [key, child] of Object.entries(value)) {
    assert(key && !dangerousKeys.has(key), `${path} contains an unsafe key`);
    count += stringLeaves(child, `${path}.${key}`);
  }
  return count;
}

function validatePack(pack, filename) {
  assert.equal(pack.format, "geolibre-language-pack", `${filename}: format`);
  assert.equal(pack.formatVersion, 1, `${filename}: formatVersion`);
  assert.equal(pack.scope, "whitebox", `${filename}: scope`);
  assert.match(pack.locale, /^[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/, `${filename}: locale`);
  assert.equal(filename, `${pack.locale}.json`, `${filename}: locale must match filename`);
  assert.deepEqual(
    Object.keys(pack.translations ?? {}),
    ["processing"],
    `${filename}: translation root`,
  );
  const processing = pack.translations.processing;
  assert(
    Object.keys(processing).every((key) => key === "toolMeta" || key === "whitebox"),
    `${filename}: unsupported Processing subtree`,
  );
  if (processing.toolMeta) assert.deepEqual(Object.keys(processing.toolMeta), ["whitebox"]);
  if (processing.whitebox) {
    assert(
      Object.keys(processing.whitebox).every((key) =>
        ["categories", "menuTool", "menuSubcategory"].includes(key),
      ),
      `${filename}: unsupported Whitebox subtree`,
    );
  }
  const leaves = stringLeaves(processing, `${filename}.translations.processing`);
  assert(leaves > 0 && leaves <= MAX_LEAVES, `${filename}: invalid message count ${leaves}`);
  return leaves;
}

const index = JSON.parse(await readFile(new URL("../v1/index.json", import.meta.url), "utf8"));
const files = (await readdir(packDirectory)).filter((name) => name.endsWith(".json")).sort();
assert.deepEqual(
  index.packs.map((entry) => `${entry.locale}.json`).sort(),
  files,
  "v1/index.json must list every pack exactly once",
);

const indexed = new Map(index.packs.map((entry) => [`${entry.locale}.json`, entry]));
const locales = JSON.parse(
  await readFile(new URL("../translations/locales.json", import.meta.url), "utf8"),
);
const english = JSON.parse(await readFile(new URL("en.json", packDirectory), "utf8")).translations
  .processing;

/**
 * Every leaf a translated pack carries must sit at a path that is a string in
 * the English pack. The app would accept an extra key without complaint and
 * simply never read it, so a pack built against an older `en.json` (a renamed
 * tool, a dropped parameter) ships dead strings instead of failing here.
 * Returns how many English leaves the pack leaves untranslated.
 */
function checkAgainstEnglish(value, source, path) {
  if (typeof value === "string") {
    assert.equal(typeof source, "string", `${path} is not a message in en.json`);
    return 0;
  }
  assert(source && typeof source === "object", `${path} is not a branch in en.json`);
  let missing = 0;
  for (const key of Object.keys(value)) {
    assert(Object.hasOwn(source, key), `${path}.${key} is not in en.json`);
    missing += checkAgainstEnglish(value[key], source[key], `${path}.${key}`);
  }
  for (const key of Object.keys(source)) {
    if (!Object.hasOwn(value, key)) missing += stringLeaves(source[key], `${path}.${key}`);
  }
  return missing;
}

for (const filename of files) {
  const bytes = await readFile(new URL(filename, packDirectory));
  assert(bytes.byteLength <= MAX_BYTES, `${filename}: exceeds the 5 MB limit`);
  const pack = JSON.parse(bytes.toString("utf8"));
  const leaves = validatePack(pack, filename);
  // The index is generated by scripts/reindex.mjs. `bytes` in particular cannot
  // be maintained by hand — it moves whenever a single string is retranslated —
  // so a stale index is a CI failure rather than a silently wrong download page.
  const entry = indexed.get(filename);
  assert.equal(entry.bytes, bytes.byteLength, `${filename}: v1/index.json is stale, run scripts/reindex.mjs`);
  assert.equal(entry.name, pack.name, `${filename}: v1/index.json name is stale`);
  assert.equal(entry.updatedAt, pack.updatedAt, `${filename}: v1/index.json updatedAt is stale`);
  assert(locales[pack.locale], `${filename}: translations/locales.json has no "${pack.locale}" entry`);
  assert.equal(entry.locale, pack.locale, `${filename}: v1/index.json locale is stale`);
  // A partial pack is shippable (i18next falls back to English per key), so it
  // is reported rather than rejected; see TRANSLATING.md.
  const missing =
    pack.locale === "en" ? 0 : checkAgainstEnglish(pack.translations.processing, english, pack.locale);
  console.log(
    `${filename}: ${leaves.toLocaleString("en")} messages, ${bytes.byteLength} bytes` +
      (missing ? `, ${missing.toLocaleString("en")} left in English` : ""),
  );
}
